[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password =
db_name =
http_port = 8075
http_interface = 127.0.0.1
addons_path = odoo_source/addons,custom_addons,community_addons/web
logfile = logs/odoo.log
log_level = info
dev_mode = reload,qweb,werkzeug,xml
data_dir = filestore
admin_passwd = $pbkdf2-sha512$600000$dc75P4cQ4lwLgfAeA4BQKg$8fvPh7TahcL5KbNmOCf4pSClvs6CR7HtTOHEfJBtO46soRkCRPenHYokRCXnC7ele.Fmh1ohv2J3vT/VWYSQlQ

